=== ruxi22/HW1-Semantic-Web/src/main/resources/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="recipes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recipe" type="RecipeType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="RecipeType">
    <xs:sequence>
      <xs:element name="title" type="xs:string">
        <xs:annotation>
          <xs:documentation>Recipe title (required)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="image" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Path to recipe image (optional)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="cuisineTypes">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="cuisineType" type="CuisineTypeString" minOccurs="2" maxOccurs="2"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="difficultyLevels">
        <xs:complexType>
          <xs:sequence>
             <xs:element name="difficultyLevel" type="DifficultyLevelString" minOccurs="1" maxOccurs="3"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Unique recipe identifier (e.g., R001)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="CuisineTypeString">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Italian"/>
      <xs:enumeration value="Spanish"/>
      <xs:enumeration value="Japanese"/>
      <xs:enumeration value="Mexican"/>
      <xs:enumeration value="Indian"/>
      <xs:enumeration value="Greek"/>
      <xs:enumeration value="Thai"/>
      <xs:enumeration value="French"/>
      <xs:enumeration value="Chinese"/>
      <xs:enumeration value="Korean"/>
      <xs:enumeration value="Vietnamese"/>
      <xs:enumeration value="Turkish"/>
      <xs:enumeration value="Brazilian"/>
      <xs:enumeration value="Lebanese"/>
      <xs:enumeration value="German"/>
      <xs:enumeration value="Moroccan"/>
      <xs:enumeration value="Peruvian"/>
      <xs:enumeration value="American"/>
      <xs:enumeration value="Asian"/>
      <xs:enumeration value="Mediterranean"/>
      <xs:enumeration value="European"/>
      <xs:enumeration value="Latin American"/>
      <xs:enumeration value="Street Food"/>
      <xs:enumeration value="Vegetarian"/>
      <xs:enumeration value="Tapas"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="DifficultyLevelString">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Beginner"/>
      <xs:enumeration value="Intermediate"/>
      <xs:enumeration value="Advanced"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== ruxi22/HW1-Semantic-Web/src/main/resources/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="recipes.xsd">
    <recipe id="R001">
        <title>Creamy pumpkin pasta</title>
        <image>/recipe-images/recipe_1.jpg</image>
        <cuisineTypes>
            <cuisineType>Chinese</cuisineType>
            <cuisineType>Japanese</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R002">
        <title>Sausage, mustard &amp; apple hash</title>
        <image>/recipe-images/recipe_2.jpg</image>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Thai</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R003">
        <title>Mushroom stroganoff</title>
        <image>/recipe-images/recipe_3.jpg</image>
        <cuisineTypes>
            <cuisineType>Mediterranean</cuisineType>
            <cuisineType>Brazilian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R004">
        <title>Beetroot &amp; feta pasta</title>
        <image>/recipe-images/recipe_4.jpg</image>
        <cuisineTypes>
            <cuisineType>Turkish</cuisineType>
            <cuisineType>Indian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>

    <recipe id="R005">
        <title>Pork &amp; apple burgers</title>
        <image>/recipe-images/recipe_5.jpg</image>
        <cuisineTypes>
            <cuisineType>Korean</cuisineType>
            <cuisineType>Thai</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R006">
        <title>Mushroom soup</title>
        <image>/recipe-images/recipe_6.jpg</image>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Vegetarian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>

    <recipe id="R007">
        <title>Squash &amp; halloumi flatbreads with sweet chilli beetroot jam</title>
        <image>/recipe-images/recipe_7.jpg</image>
        <cuisineTypes>
            <cuisineType>Latin American</cuisineType>
            <cuisineType>French</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R008">
        <title>Simple squash risotto</title>
        <image>/recipe-images/recipe_8.jpg</image>
        <cuisineTypes>
            <cuisineType>Mediterranean</cuisineType>
            <cuisineType>Spanish</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R009">
        <title>Slow cooker spiced root &amp; lentil casserole</title>
        <image>/recipe-images/recipe_9.jpg</image>
        <cuisineTypes>
            <cuisineType>Latin American</cuisineType>
            <cuisineType>Italian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>

    <recipe id="R010">
        <title>Squash &amp; spinach fusilli with pecans</title>
        <image>/recipe-images/recipe_10.jpg</image>
        <cuisineTypes>
            <cuisineType>Korean</cuisineType>
            <cuisineType>Indian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R011">
        <title>Easy vegetable curry</title>
        <image>/recipe-images/recipe_11.jpg</image>
        <cuisineTypes>
            <cuisineType>German</cuisineType>
            <cuisineType>Tapas</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R012">
        <title>Sausage &amp; butternut squash shells</title>
        <image>/recipe-images/recipe_12.jpg</image>
        <cuisineTypes>
            <cuisineType>Turkish</cuisineType>
            <cuisineType>American</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R013">
        <title>Autumn vegetable soup with cheesy toasts</title>
        <image>/recipe-images/recipe_13.jpg</image>
        <cuisineTypes>
            <cuisineType>American</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R014">
        <title>Mushroom &amp; sausage pasta</title>
        <image>/recipe-images/recipe_14.jpg</image>
        <cuisineTypes>
            <cuisineType>American</cuisineType>
            <cuisineType>Korean</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R015">
        <title>Creamy pumpkin &amp; lentil soup</title>
        <image>/recipe-images/recipe_15.jpg</image>
        <cuisineTypes>
            <cuisineType>Greek</cuisineType>
            <cuisineType>Latin American</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R016">
        <title>Curried parsnip soup</title>
        <image>/recipe-images/recipe_16.jpg</image>
        <cuisineTypes>
            <cuisineType>European</cuisineType>
            <cuisineType>Lebanese</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R017">
        <title>Red onion gravy</title>
        <image>/recipe-images/recipe_17.jpg</image>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Indian</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R018">
        <title>Butternut squash pilaf</title>
        <image>/recipe-images/recipe_18.jpg</image>
        <cuisineTypes>
            <cuisineType>Vietnamese</cuisineType>
            <cuisineType>French</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Advanced</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R019">
        <title>Sausage &amp; maple swede traybake</title>
        <image>/recipe-images/recipe_19.jpg</image>
        <cuisineTypes>
            <cuisineType>Asian</cuisineType>
            <cuisineType>Latin American</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Intermediate</difficultyLevel>
            <difficultyLevel>Advanced</difficultyLevel>
        </difficultyLevels>
    </recipe>
    <recipe id="R020">
        <title>Cauliflower mac &amp; cheese</title>
        <image>/recipe-images/recipe_20.jpg</image>
        <cuisineTypes>
            <cuisineType>Moroccan</cuisineType>
            <cuisineType>Turkish</cuisineType>
        </cuisineTypes>
        <difficultyLevels>
            <difficultyLevel>Beginner</difficultyLevel>
            <difficultyLevel>Intermediate</difficultyLevel>
        </difficultyLevels>
    </recipe>
</recipes>
